In [1]:
import sys
sys.path.append('../utilities/')
import pandas as pd
import numpy as np
from sklearn import svm
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score
import torch
from sentence_transformers import SentenceTransformer
from joblib import dump
from openai import OpenAI
from tqdm import tqdm
from mmd import MMD
import re
from sklearn.feature_extraction.text import CountVectorizer

/Users/pranitgunjal/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [2]:
sentence_transformer = SentenceTransformer('all-mpnet-base-v2')

# **Data Pre-processing**

In [3]:
train_df = pd.read_csv('../data/initial_datasets/dota2/dota2_grouped_train.csv')
test_df = pd.read_csv('../data/initial_datasets/dota2/dota2_grouped_test.csv')

In [5]:
train_df

     match  player                                 translated_message  label
0       33       1  "hp?". "first bash". haha. "Me too". "alright ...      0
1       76       5  "What the fuck". "what 2 suicides". "he left"....      0
2       28       3  xd. "easy mid". report lion carry. "easy oof"....      1
3       77       2                                                 gg      0
4        4       8                        Well played.. "Well played"      0
..     ...     ...                                                ...    ...
245     41       1  "report invoker". "Feeding with the courier". ...      1
246      8       5                                       Gg. 0-20. gg      0
247     54       3  "the moment the guy fell". "damn booster". "de...      0
248     10       9  "Who are you talking to?". "ha?" translates to...      0
249     89       5  "Go talk shit)". easy. "Got distracted by the ...      1

[250 rows x 4 columns]

In [4]:
test_df

     match  player                                 translated_message  label
0       83       4                                         end please      0
1       22       0  "TERROR". "HOW DID YOU FARM?". "COMPLETELY EAS...      1
2        5       5  _. lol. bad computer. "noob". "Easy". EZ. "E...      0
3       92       5                          no. "Am I to blame?". lol      0
4       40       5  "send the channel ". "or on Twitch?". "shut t...      1
..     ...     ...                                                ...    ...
245     23       1                   I'm buying this Assault Cuirass.      0
246     87       3                                       REPORT NOOBS      0
247     12       2                                               easy      0
248     58       9  It's like 4% to get two bashes in a row.. and ...      0
249     13       6                                                 gg      0

[250 rows x 4 columns]

In [3]:
df = pd.read_csv('../data/initial_datasets/dota2_train_labels_translated_sanitized.csv')

In [4]:
df['label'] = df['label'].replace({'x': 1})
df['label'] = df['label'].fillna(0)
df['label'] = df['label'].astype(int)

/var/folders/lv/pnwq6bmj4tq68bsvy__37qyh0000gn/T/ipykernel_91964/2336875256.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['label'] = df['label'].replace({'x': 1})

In [7]:
test_df = df[['translated_message', 'label']].sample(n=1000)

In [10]:
train_df = df.drop(test_df.index)

In [17]:
train_df = train_df[['translated_message', 'label']]

In [22]:
df['label'].value_counts() / df.shape[0]

label
0    0.959815
1    0.040185
Name: count, dtype: float64

# **Classifier**

In [6]:
n = [10, 50, 100, 200]

In [8]:
for ni in n:
    train_sample = train_df.sample(n=ni)
    X_train = np.array(sentence_transformer.encode(train_sample['translated_message'].to_list()))
    y_train = train_sample['label']

    X_test = np.array(sentence_transformer.encode(test_df['translated_message'].to_list()))
    y_test = test_df['label']

    model = svm.SVC(kernel='linear', probability=True, class_weight='balanced')
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    test_acc = accuracy_score(y_test, y_pred)

    print(ni)
    print(f"Test Acc: {test_acc}")

    y_prob = model.predict_proba(X_test)[:, 1]
    print(f"Roc Auc: {roc_auc_score(y_test, y_prob)}")

    print(f"Precision: {precision_score(y_test, y_pred)}")
    print(f"Recall: {recall_score(y_test, y_pred)}")

10
Test Acc: 0.864
Roc Auc: 0.1922923588039867
Precision: 0.5454545454545454
Recall: 0.17142857142857143
50
Test Acc: 0.82
Roc Auc: 0.8299003322259136
Precision: 0.38095238095238093
Recall: 0.45714285714285713
100
Test Acc: 0.82
Roc Auc: 0.8672425249169435
Precision: 0.4166666666666667
Recall: 0.7142857142857143
200
Test Acc: 0.816
Roc Auc: 0.8803986710963455
Precision: 0.4
Recall: 0.6285714285714286

In [48]:
train_sample = train_df.sample(n=n)

In [49]:
train_sample['label'].value_counts()

label
0    185
1     15
Name: count, dtype: int64

In [53]:
X_train = np.array(sentence_transformer.encode(train_sample['translated_message'].to_list()))
y_train = train_sample['label']

KeyboardInterrupt:

In [51]:
X_test = np.array(sentence_transformer.encode(test_df['translated_message'].to_list()))
y_test = test_df['label']

In [52]:
model = svm.SVC(kernel='linear', probability=True, class_weight='balanced')
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
test_acc = accuracy_score(y_test, y_pred)
print(f"Test Acc: {test_acc}")

print(precision_score(y_test, y_pred))
print(recall_score(y_test, y_pred))

y_prob = model.predict_proba(X_test)[:, 1]
print(roc_auc_score(y_test, y_prob))

Test Acc: 0.933
0.21818181818181817
0.3333333333333333
0.8908050945136007