In [2]:
import sys
sys.path.append('../utilities/')
import pandas as pd
import numpy as np
from sklearn import svm
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score
import torch
from sentence_transformers import SentenceTransformer
from joblib import dump
from openai import OpenAI
from tqdm import tqdm
from mmd import MMD
import re
from sklearn.feature_extraction.text import CountVectorizer
import random

/Users/pranitgunjal/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [3]:
sentence_transformer = SentenceTransformer('all-mpnet-base-v2')

# **Data Pre-processing**

In [4]:
train_df = pd.read_csv('../data/initial_datasets/dota2/dota2_train.csv')
test_df = pd.read_csv('../data/initial_datasets/dota2/dota2_test.csv')

In [42]:
train_df = pd.read_csv('../data/initial_datasets/reddit/reddit_train.csv')
test_df = pd.read_csv('../data/initial_datasets/reddit/reddit_test.csv')

In [43]:
train_df

                                                messages  labels
0                                        That game hurt.       1
1                                     Man I love reddit.       0
2      Right? Considering it’s such an important docu...       0
3      He isn't as big, but he's still quite popular....       1
4      That's crazy; I went to a super [RELIGION] hig...       0
...                                                  ...     ...
40696  Oh man is this true. Coffee has a seriously ne...       1
40697                            You’re good, no worries       0
40698  one's a rapist, and the other's a stingy yank ...       1
40699  This is great! Can anyone make a request with ...       0
40700  This is so cruel. I literally feel physically ...       1

[40701 rows x 2 columns]

In [44]:
test_df

                                              messages  labels
0                                   First is the worst       1
1    Our education system has been a complete and u...       1
2    The fuck you call me!? A cunt!? Damn man, didn...       1
3    It will probably take him some time to figure ...       0
4    Somebody is really insecure about their career...       1
..                                                 ...     ...
995                 Be glad you don't know the answer.       0
996  I’m laughing more that I feel I should st this...       0
997  I wouldnt necessarily call you and addict but ...       1
998  I'm genuinely interested in the responses to t...       0
999  I hope things get better soon. I'm proud of yo...       0

[1000 rows x 2 columns]

In [3]:
df = pd.read_csv('../data/initial_datasets/dota2_train_labels_translated_sanitized.csv')

In [4]:
df['label'] = df['label'].replace({'x': 1})
df['label'] = df['label'].fillna(0)
df['label'] = df['label'].astype(int)

/var/folders/lv/pnwq6bmj4tq68bsvy__37qyh0000gn/T/ipykernel_91964/2336875256.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['label'] = df['label'].replace({'x': 1})

In [7]:
test_df = df[['translated_message', 'label']].sample(n=1000)

In [10]:
train_df = df.drop(test_df.index)

In [17]:
train_df = train_df[['translated_message', 'label']]

In [22]:
df['label'].value_counts() / df.shape[0]

label
0    0.959815
1    0.040185
Name: count, dtype: float64

# **Classifier**

In [9]:
n = [10, 50, 100, 200]

In [13]:
seeds = [random.randint(0, 2**32 - 1) for _ in range(3)]

In [23]:
train_df.shape[0]

2460

In [28]:
train_df.drop(one_label.index)

                                               messages  labels
0                                              "faggot"       0
1                                    "there's a monkey"       0
2             "Sniper, how do you like our mid player?"       0
3                            "You're all corpses, guys"       0
4                                             "Not bad"       0
...                                                 ...     ...
2455  "my Luna hits the one with leggings, now I see...       0
2456                                                 GG       0
2457            "my shadow doesn't know how to use ult"       0
2458                                                 GG       0
2459                                  GG REPORT SLARDAR       0

[2459 rows x 2 columns]

In [ ]:
one_label = train_df[train_df['labels'] == 1].sample(n=1, random_state=42)
rest = train_df.drop(one_label.index)

rest_sample = rest.sample(n=9, random_state=42)
train_sample = pd.concat([one_label, rest_sample])

                            messages  labels
352      "HERALD ANDERSON IS STUPID"       1
757                           ALMOST       0
643   "Am I the carry or something?"       0
2403                             lol       0
1945                            easy       0
252                            ":?D"       0
354           "LC, duel over there."       0
1317                    "I'm a noob"       0
1643                             wtf       0
237                   "F*CK YEAH!!!"       0

In [39]:
train_sample['labels'].value_counts()[1]

np.int64(9)

In [ ]:
dota2_seeds = [367402242, 1881848525, 360375685]

In [41]:
print(seeds)

[367402242, 1881848525, 360375685]

In [45]:
seeds = [random.randint(0, 2**32 - 1) for _ in range(3)]
for ni in n:
    prec = 0
    recall = 0
    roc_auc = 0
    print(ni)
    for seed in seeds:
        one_label = train_df[train_df['labels'] == 1].sample(n=1, random_state=seed)
        rest = train_df.drop(one_label.index)

        rest_sample = rest.sample(n=(ni-1), random_state=seed)
        train_sample = pd.concat([one_label, rest_sample])
        # print(train_sample['labels'].value_counts()[0])
        # print(train_sample['labels'].value_counts()[1])
        X_train = np.array(sentence_transformer.encode(train_sample['messages'].to_list()))
        y_train = train_sample['labels']

        X_test = np.array(sentence_transformer.encode(test_df['messages'].to_list()))
        y_test = test_df['labels']

        model = svm.SVC(kernel='linear', probability=True, class_weight='balanced')
        model.fit(X_train, y_train)

        y_pred = model.predict(X_test)
        test_acc = accuracy_score(y_test, y_pred)

        # print(ni)
        # print(f"Test Acc: {test_acc}")

        y_prob = model.predict_proba(X_test)[:, 1]
        roc_auc += roc_auc_score(y_test, y_prob)
        prec += precision_score(y_test, y_pred)
        recall += precision_score(y_test, y_pred)
    
    print(f"Roc_Auc: {roc_auc/3}")
    print(f"Precision: {prec/3}")
    print(f"Recall: {recall/3}")

10
Roc_Auc: 0.4455947385675653
Precision: 0.39838951785959686
Recall: 0.39838951785959686
50
Roc_Auc: 0.43419272544547943
Precision: 0.5547979027211979
Recall: 0.5547979027211979
100
Roc_Auc: 0.772140835512951
Precision: 0.5883436441271567
Recall: 0.5883436441271567
200
Roc_Auc: 0.7928933726738219
Precision: 0.6117288904742088
Recall: 0.6117288904742088

In [48]:
train_sample = train_df.sample(n=n)

In [49]:
train_sample['label'].value_counts()

label
0    185
1     15
Name: count, dtype: int64

In [53]:
X_train = np.array(sentence_transformer.encode(train_sample['translated_message'].to_list()))
y_train = train_sample['label']

KeyboardInterrupt:

In [51]:
X_test = np.array(sentence_transformer.encode(test_df['translated_message'].to_list()))
y_test = test_df['label']

In [52]:
model = svm.SVC(kernel='linear', probability=True, class_weight='balanced')
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
test_acc = accuracy_score(y_test, y_pred)
print(f"Test Acc: {test_acc}")

print(precision_score(y_test, y_pred))
print(recall_score(y_test, y_pred))

y_prob = model.predict_proba(X_test)[:, 1]
print(roc_auc_score(y_test, y_prob))

Test Acc: 0.933
0.21818181818181817
0.3333333333333333
0.8908050945136007

In [48]:
roc_auc = 0
prec = 0
recall = 0
seeds = [random.randint(0, 2**32 - 1) for _ in range(3)]
for seed in seeds:
    train_sample = train_df.sample(n=1000, random_state=seed)
    X_train = np.array(sentence_transformer.encode(train_sample['messages'].to_list()))
    y_train = train_sample['labels']

    X_test = np.array(sentence_transformer.encode(test_df['messages'].to_list()))
    y_test = test_df['labels']

    model = svm.SVC(kernel='linear', probability=True, class_weight='balanced')
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    test_acc = accuracy_score(y_test, y_pred)

    y_prob = model.predict_proba(X_test)[:, 1]
    roc_auc += roc_auc_score(y_test, y_prob)
    prec += precision_score(y_test, y_pred)
    recall += precision_score(y_test, y_pred)

print(roc_auc / 3)
print(prec / 3)
print(recall / 3)

0.8263678621994884
0.6078898585130313
0.6078898585130313