In [2]:
import sys
sys.path.append('../utilities/')

In [3]:
import pandas as pd
import numpy as np
from sklearn import svm
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score
from sentence_transformers import SentenceTransformer
from joblib import dump
from openai import OpenAI
from tqdm import tqdm
from mmd import MMD
import torch
import json

/Users/pranitgunjal/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

# **First Classifier**

In [5]:
df = pd.read_csv('../data/initial_datasets/reddit/reddit_binary_labels.csv')

In [12]:
sentence_transformer = SentenceTransformer('all-mpnet-base-v2')

In [7]:
sample_df = df.sample(n=1000, random_state=42)

In [8]:
transformer = SentenceTransformer('all-mpnet-base-v2')
X = np.array(transformer.encode(sample_df['text'].to_list()))
y = np.array(sample_df['label'].to_list())

# **MMD**

In [18]:
def report_MMD(X, Y, normalize=False):
    
    tensorX = torch.tensor(X)
    tensorY = torch.tensor(Y)
    rbf_mmd = MMD(tensorX, tensorY, "rbf")
    scale_mmd = MMD(tensorX, tensorY, "multiscale")


    if normalize:
        return (rbf_mmd.item() / np.sqrt((1.0 / X.shape[0]) + (1.0 / Y.shape[0]))), (scale_mmd.item() / np.sqrt(1.0 / X.shape[0] + 1.0 / Y.shape[0]))
    else:
        return rbf_mmd.item(), scale_mmd.item()

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [11]:
model = svm.SVC(kernel='linear', probability=True, class_weight='balanced', random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_train)
train_acc = accuracy_score(y_pred, y_train)
print(f'Train acc: {train_acc}')

y_pred = model.predict(X_test)
test_acc = accuracy_score(y_pred, y_test)
print(f'Test acc: {test_acc}')

Train acc: 0.8685714285714285
Test acc: 0.77

In [11]:
param_grid = {
    'C': [10**(i) for i in range(-2, 3)],
    'kernel': ['linear', 'poly', 'rbf'],
    'gamma': ['scale', 'auto'],
    'degree': [2, 3, 4],
}

In [19]:
model = svm.SVC(probability=True)

grid_search = GridSearchCV(estimator=model, param_grid=param_grid, verbose=0, scoring='accuracy', cv=5, n_jobs=-1)
grid_search.fit(X_train, y_train)
print(grid_search.best_score_)
print(grid_search.best_params_)

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

0.7685714285714286
{'C': 1, 'degree': 2, 'gamma': 'scale', 'kernel': 'linear'}

In [ ]:
y_pred = model.predict(X_train)
train_acc = accuracy_score(y_pred, y_train)
print(f'Train acc: {train_acc}')

y_pred = model.predict(X_test)
test_acc = accuracy_score(y_pred, y_test)
print(f'Test acc: {test_acc}')

In [25]:
best_model = grid_search.best_estimator_

In [14]:
y_pred = model.predict(X_train)
train_acc = accuracy_score(y_pred, y_train)
print(f'Train acc: {train_acc}')

y_pred = model.predict(X_test)
test_acc = accuracy_score(y_pred, y_test)
print(f'Test acc: {test_acc}')

Train acc: 0.8685714285714285
Test acc: 0.77

In [15]:
print(precision_score(y_test, y_pred))
print(recall_score(y_test, y_pred))

0.8764705882352941
0.7563451776649747

In [17]:
y_prob = model.predict_proba(X_test)[:, 1]
print(roc_auc_score(y_test, y_prob))

0.8582376423044701

# **Control Classifier**

In [ ]:
pd.read_csv('../data/initial_datasets/reddit/reddit_test.csv')

In [6]:
gen_df = pd.read_csv('../data/generated/reddit/token_co_occurences/token_co_occurences.csv')
orig_df = pd.read_csv('../data/initial_datasets/reddit/reddit_test.csv')
orig_df = orig_df.sample(n=1000)

In [21]:
gen_df = gen_df.sample(n=1000)

In [7]:
orig_df

                                                  text  label
702                               What a rollercoaster      1
401  Everyone knew that deal was stupid from the mo...     -1
932                  Don't torture yourself like that.     -1
681  Thank you for this very informative answer. I ...     -1
738  Did you just equate the tomahawk chant to lync...      1
..                                                 ...    ...
747  You really are this stupid aren’t you? Whateve...     -1
337  Yeah, my thoughts exactly. Alright people, tim...      1
619  As much as I’d love [NAME] to be gone, i know ...     -1
975  A beautiful wonder of nature. Dress prices hav...      1
595  Oligarch-sponsored? [NAME], stop throwing buzz...     -1

[1000 rows x 2 columns]

In [8]:
gen_df['type'] = 'synthetic'
orig_df['type'] = 'original'

In [9]:
orig_df.rename(columns={'text': 'sentences', 'label': 'labels'}, inplace=True)

## **Only Synth Classifier**

In [22]:
train_df = gen_df
test_df = orig_df

X_train = train_df['sentences']
y_train = train_df['labels']

X_test = test_df['sentences']
y_test = test_df['labels']

In [23]:
X_train = np.array(sentence_transformer.encode(X_train.to_list()))
X_test = np.array(sentence_transformer.encode(X_test.to_list()))

In [24]:
model = svm.SVC(kernel='linear', probability=True, class_weight='balanced')
model.fit(X_train, y_train)

y_pred = model.predict(X_train)
train_acc = accuracy_score(y_pred, y_train)
print(f'Train acc: {train_acc}')

y_pred = model.predict(X_test)
test_acc = accuracy_score(y_pred, y_test)
print(f'Test acc: {test_acc}')

Train acc: 0.998
Test acc: 0.681

In [25]:
print(precision_score(y_test, y_pred))
print(recall_score(y_test, y_pred))

0.90625
0.5515055467511886

In [26]:
y_prob = model.predict_proba(X_test)[:, 1]
print(roc_auc_score(y_test, y_prob))

0.8243786479069228

In [28]:
report_MMD(X_train, X_test, True)

(np.float64(0.43479146950953684), np.float64(1.6405812999056941))

In [30]:
import numpy as np
import ot

def wasserstein(X, Y):
    
    a = np.ones((X.shape[0],)) / X.shape[0]
    b = np.ones((Y.shape[0],)) / Y.shape[0]

    M = ot.dist(X, Y)
    M /= M.max()

    return ot.emd2(a, b, M)

In [31]:
wasserstein(X_train, X_test)

0.5310973137915133

## **Only Synth + 100 Samples**

In [32]:
orig_train_df = pd.read_csv('../data/initial_datasets/reddit/reddit_train.csv')
orig_train_df['type'] = 'original'
orig_train_df = orig_train_df.sample(n=100, random_state=42)

In [33]:
orig_train_df.rename(columns={'text': 'sentences', 'label': 'labels'}, inplace=True)

In [34]:
train_df = pd.concat([gen_df.sample(n=900), orig_train_df]).sample(frac=1).reset_index(drop=True)
test_df = orig_df.sample(frac=1).reset_index(drop=True)

X_train = train_df['sentences']
X_test = test_df['sentences']

y_train = train_df['labels']
y_test = test_df['labels']

In [35]:
X_train = np.array(sentence_transformer.encode(X_train.to_list()))
X_test = np.array(sentence_transformer.encode(X_test.to_list()))

In [36]:
model = svm.SVC(kernel='linear', probability=True, class_weight='balanced', random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_train)
train_acc = accuracy_score(y_pred, y_train)
print(f'Train acc: {train_acc}')

y_pred = model.predict(X_test)
test_acc = accuracy_score(y_pred, y_test)
print(f'Test acc: {test_acc}')

Train acc: 0.989
Test acc: 0.739

In [37]:
print(precision_score(y_test, y_pred))
print(recall_score(y_test, y_pred))

0.8375912408759124
0.7274167987321711

In [38]:
y_prob = model.predict_proba(X_test)[:, 1]
print(roc_auc_score(y_test, y_prob))

0.814968712286172

In [19]:
orig_df

                                               sentences  labels
6729   The way that ladder is attached to the buildin...      -1
33148  The left solution is to make them all citizens...      -1
25660  Me too! They were half off at the grocery stor...       1
11460  She forced him to sing a valentine song by thr...       1
5842    It is actually out on the steam store right now.       1
...                                                  ...     ...
34084                              What absolute garbage      -1
28297  Reminds me of that last scene in Coraline, whe...       1
804    "If you don't support no go zones, you are rac...      -1
27159  That is absurd, man. I'm sorry you don't belie...      -1
15401  you can tell she's insanely insecure by her bo...      -1

[1000 rows x 2 columns]

In [20]:
sample_df

                                                    text  label
13205  I used it for a while. It made me way more soc...      1
23193     Now this is a Contrapoints video I want to see      1
33371  May [NAME] bless and keep the President... far...      1
38983  The main reason I left is a hidden mmr used to...     -1
29165  I'm glad you could relate and that you also fo...      1
...                                                  ...    ...
22908  You can. I've used my Kroger-linked phone numb...      1
27778       I liked it better when [NAME] was half naked     -1
9024   [NAME] game sucks. He's good at comps but his ...      1
22259  >[NAME] One of the most horrifying stories I'v...      1
6504                          Which makes zero sense lol      1

[1000 rows x 2 columns]

In [9]:
orig_dist = np.array(sentence_transformer.encode(orig_df['sentences'].to_list()))
sample_dist = np.array(sentence_transformer.encode(gen_df['sentences'].to_list()))

In [52]:
report_MMD(orig_dist, sample_dist, normalize=True)

NameError: name 'orig_dist' is not defined

In [12]:
gen_df = pd.read_csv('../data/generated/reddit/privacy_protected/new_reddit_agg_stats_gen.csv')
orig_df = pd.read_csv('../data/initial_datasets/reddit_binary_labels.csv')
orig_df = orig_df.sample(n=1000)

In [13]:
orig_df.rename(columns={'text': 'sentences', 'label': 'labels'}, inplace=True)

In [14]:
orig_dist = np.array(sentence_transformer.encode(orig_df['sentences'].to_list()))
sample_dist = np.array(sentence_transformer.encode(gen_df['sentences'].to_list()))

In [10]:
import numpy as np
import ot

def wasserstein(X, Y):
    
    a = np.ones((X.shape[0],)) / X.shape[0]
    b = np.ones((Y.shape[0],)) / Y.shape[0]

    M = ot.dist(X, Y)
    M /= M.max()

    return ot.emd2(a, b, M)

In [15]:
wasserstein(orig_dist, sample_dist)

0.5408510427325971